[package]
name = "wrapper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quizx = { path = "../quizx/quizx" }
num-complex = "0.4"
approx = "0.5.1"