//
// Generated by JTB 1.3.2
//

package visitor;
import syntaxtree.*;
import java.util.*;

/**
 * Provides default methods which visit each node in the tree in depth-first
 * order.  Your visitors may extend this class.
 */
public class DepthFirstVisitor implements Visitor {
   //
   // Auto class visitors--probably don't need to be overridden.
   //
   public void visit(NodeList n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeListOptional n) {
      if ( n.present() )
         for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
            e.nextElement().accept(this);
   }

   public void visit(NodeOptional n) {
      if ( n.present() )
         n.node.accept(this);
   }

   public void visit(NodeSequence n) {
      for ( Enumeration<Node> e = n.elements(); e.hasMoreElements(); )
         e.nextElement().accept(this);
   }

   public void visit(NodeToken n) { }

   //
   // User-generated visitor methods below
   //

   /**
    * f0 -> Init()
    * f1 -> ( Instruction() )*
    * f2 -> [ Assertion() ]
    * f3 -> Measure()
    * f4 -> <EOF>
    */
   public void visit(Goal n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
   }

   /**
    * f0 -> "circuit"
    * f1 -> ":"
    * f2 -> IntegerLiteral()
    * f3 -> "qubits"
    */
   public void visit(Init n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> OneQubitInstruction()
    *       | TwoQubitInstruction()
    *       | ThreeQubitInstruction()
    */
   public void visit(Instruction n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> OneQubitGate()
    * f1 -> "("
    * f2 -> IntegerLiteral()
    * f3 -> ")"
    */
   public void visit(OneQubitInstruction n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> TwoQubitGate()
    * f1 -> "("
    * f2 -> IntegerLiteral()
    * f3 -> ","
    * f4 -> IntegerLiteral()
    * f5 -> ")"
    */
   public void visit(TwoQubitInstruction n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> ThreeQubitGate()
    * f1 -> "("
    * f2 -> IntegerLiteral()
    * f3 -> ","
    * f4 -> IntegerLiteral()
    * f5 -> ","
    * f6 -> IntegerLiteral()
    * f7 -> ")"
    */
   public void visit(ThreeQubitInstruction n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
   }

   /**
    * f0 -> "H"
    *       | "T"
    *       | "X"
    *       | "Z"
    *       | "D"
    *       | "S"
    */
   public void visit(OneQubitGate n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "CNOT"
    *       | "CZ"
    */
   public void visit(TwoQubitGate n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "CCNOT"
    *       | "NCCNOT"
    *       | "CNCNOT"
    *       | "NCNCNOT"
    */
   public void visit(ThreeQubitGate n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "assert"
    * f1 -> "state"
    * f2 -> "in"
    * f3 -> "span"
    * f4 -> "{"
    * f5 -> AVector()
    * f6 -> ","
    * f7 -> AVector()
    * f8 -> "}"
    */
   public void visit(Assertion n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
      n.f7.accept(this);
      n.f8.accept(this);
   }

   /**
    * f0 -> Component()
    * f1 -> ( Component() )*
    */
   public void visit(AVector n) {
      n.f0.accept(this);
      n.f1.accept(this);
   }

   /**
    * f0 -> BracketedComponent()
    *       | Ket()
    */
   public void visit(Component n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> [ Amplitude() ]
    * f2 -> Ket()
    * f3 -> "+"
    * f4 -> [ Amplitude() ]
    * f5 -> Ket()
    * f6 -> ")"
    */
   public void visit(BracketedComponent n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
      n.f6.accept(this);
   }

   /**
    * f0 -> Real()
    *       | Complex()
    */
   public void visit(Amplitude n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "|"
    * f1 -> ( KetContent() )+
    * f2 -> ">"
    */
   public void visit(Ket n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
   }

   /**
    * f0 -> IntegerLiteral()
    *       | "+"
    *       | "-"
    */
   public void visit(KetContent n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "("
    * f1 -> Real()
    * f2 -> "+"
    * f3 -> Real()
    * f4 -> "i"
    * f5 -> ")"
    */
   public void visit(Complex n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
      n.f4.accept(this);
      n.f5.accept(this);
   }

   /**
    * f0 -> [ Sign() ]
    * f1 -> IntegerLiteral()
    * f2 -> "."
    * f3 -> IntegerLiteral()
    */
   public void visit(Real n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> "-"
    */
   public void visit(Sign n) {
      n.f0.accept(this);
   }

   /**
    * f0 -> "measure"
    * f1 -> IntegerLiteral()
    * f2 -> ".."
    * f3 -> IntegerLiteral()
    */
   public void visit(Measure n) {
      n.f0.accept(this);
      n.f1.accept(this);
      n.f2.accept(this);
      n.f3.accept(this);
   }

   /**
    * f0 -> <INTEGER_LITERAL>
    */
   public void visit(IntegerLiteral n) {
      n.f0.accept(this);
   }

}
