//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> "("
 * f1 -> Real()
 * f2 -> "+"
 * f3 -> Real()
 * f4 -> "i"
 * f5 -> ")"
 */
public class Complex implements Node {
   public NodeToken f0;
   public Real f1;
   public NodeToken f2;
   public Real f3;
   public NodeToken f4;
   public NodeToken f5;

   public Complex(NodeToken n0, Real n1, NodeToken n2, Real n3, NodeToken n4, NodeToken n5) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
      f5 = n5;
   }

   public Complex(Real n0, Real n1) {
      f0 = new NodeToken("(");
      f1 = n0;
      f2 = new NodeToken("+");
      f3 = n1;
      f4 = new NodeToken("i");
      f5 = new NodeToken(")");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

