//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> Init()
 * f1 -> ( Instruction() )*
 * f2 -> [ Assertion() ]
 * f3 -> Measure()
 * f4 -> <EOF>
 */
public class Goal implements Node {
   public Init f0;
   public NodeListOptional f1;
   public NodeOptional f2;
   public Measure f3;
   public NodeToken f4;

   public Goal(Init n0, NodeListOptional n1, NodeOptional n2, Measure n3, NodeToken n4) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = n4;
   }

   public Goal(Init n0, NodeListOptional n1, NodeOptional n2, Measure n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
      f4 = new NodeToken("");
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

