//
// Generated by JTB 1.3.2
//

package syntaxtree;

/**
 * Grammar production:
 * f0 -> [ Sign() ]
 * f1 -> IntegerLiteral()
 * f2 -> "."
 * f3 -> IntegerLiteral()
 */
public class Real implements Node {
   public NodeOptional f0;
   public IntegerLiteral f1;
   public NodeToken f2;
   public IntegerLiteral f3;

   public Real(NodeOptional n0, IntegerLiteral n1, NodeToken n2, IntegerLiteral n3) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
      f3 = n3;
   }

   public Real(NodeOptional n0, IntegerLiteral n1, IntegerLiteral n2) {
      f0 = n0;
      f1 = n1;
      f2 = new NodeToken(".");
      f3 = n2;
   }

   public void accept(visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

